// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "rocq-prover";
export const name = "vsrocq";
export const version = "2.4.3";
export const displayName = "VsRocq";
export const description =
    "VsRocq is an extension for Visual Studio Code with support for the Rocq Prover";
export const extensionId = `${publisher}.${name}`;

/**
 * Type union of all commands
 */
export type CommandKey =
    | "extension.rocq.showManual"
    | "extension.rocq.walkthrough"
    | "extension.rocq.showSetup"
    | "extension.rocq.showLog"
    | "extension.rocq.reset"
    | "extension.rocq.query.search"
    | "extension.rocq.query.about"
    | "extension.rocq.query.check"
    | "extension.rocq.query.locate"
    | "extension.rocq.query.print"
    | "extension.rocq.interpretToPoint"
    | "extension.rocq.interpretToEnd"
    | "extension.rocq.stepForward"
    | "extension.rocq.stepBackward"
    | "extension.rocq.displayProofView"
    | "extension.rocq.documentState"
    | "extension.rocq.addQueryTab"
    | "extension.rocq.collapseAllQueries"
    | "extension.rocq.expandAllQueries"
    | "extension.rocq.interrupt";

/**
 * Commands map registered by `rocq-prover.vsrocq`
 */
export const commands = {
    /**
     * Docs: Show manual
     * @value `extension.rocq.showManual`
     */
    extensionRocqShowManual: "extension.rocq.showManual",
    /**
     * Docs: Show setup guide
     * @value `extension.rocq.walkthrough`
     */
    extensionRocqWalkthrough: "extension.rocq.walkthrough",
    /**
     * Troubleshooting: Show setup
     * @value `extension.rocq.showSetup`
     */
    extensionRocqShowSetup: "extension.rocq.showSetup",
    /**
     * Troubleshooting: Show Log Output
     * @value `extension.rocq.showLog`
     */
    extensionRocqShowLog: "extension.rocq.showLog",
    /**
     * Reset
     * @value `extension.rocq.reset`
     */
    extensionRocqReset: "extension.rocq.reset",
    /**
     * Search
     * @value `extension.rocq.query.search`
     */
    extensionRocqQuerySearch: "extension.rocq.query.search",
    /**
     * About
     * @value `extension.rocq.query.about`
     */
    extensionRocqQueryAbout: "extension.rocq.query.about",
    /**
     * Check
     * @value `extension.rocq.query.check`
     */
    extensionRocqQueryCheck: "extension.rocq.query.check",
    /**
     * Locate
     * @value `extension.rocq.query.locate`
     */
    extensionRocqQueryLocate: "extension.rocq.query.locate",
    /**
     * Print
     * @value `extension.rocq.query.print`
     */
    extensionRocqQueryPrint: "extension.rocq.query.print",
    /**
     * Interpret to point
     * @value `extension.rocq.interpretToPoint`
     */
    extensionRocqInterpretToPoint: "extension.rocq.interpretToPoint",
    /**
     * Interpret to end
     * @value `extension.rocq.interpretToEnd`
     */
    extensionRocqInterpretToEnd: "extension.rocq.interpretToEnd",
    /**
     * Step Forward
     * @value `extension.rocq.stepForward`
     */
    extensionRocqStepForward: "extension.rocq.stepForward",
    /**
     * Step Backward
     * @value `extension.rocq.stepBackward`
     */
    extensionRocqStepBackward: "extension.rocq.stepBackward",
    /**
     * Display Proof View
     * @value `extension.rocq.displayProofView`
     */
    extensionRocqDisplayProofView: "extension.rocq.displayProofView",
    /**
     * Troubleshooting: Get current document state
     * @value `extension.rocq.documentState`
     */
    extensionRocqDocumentState: "extension.rocq.documentState",
    /**
     * Add Tab
     * @value `extension.rocq.addQueryTab`
     */
    extensionRocqAddQueryTab: "extension.rocq.addQueryTab",
    /**
     * Collapse All
     * @value `extension.rocq.collapseAllQueries`
     */
    extensionRocqCollapseAllQueries: "extension.rocq.collapseAllQueries",
    /**
     * Expand All
     * @value `extension.rocq.expandAllQueries`
     */
    extensionRocqExpandAllQueries: "extension.rocq.expandAllQueries",
    /**
     * Interrupt
     * @value `extension.rocq.interrupt`
     */
    extensionRocqInterrupt: "extension.rocq.interrupt",
} satisfies Record<string, CommandKey>;

/**
 * Type union of all languages
 */
export type LanguageKey = "rocq" | "coq-project";

/**
 * Languages map registed by `rocq-prover.vsrocq`
 */
export const languages = {
    rocq: "rocq",
    coqProject: "coq-project",
} satisfies Record<string, LanguageKey>;

/**
 * Type union of all configs
 */
export type ConfigKey =
    | "vsrocq-language-server.trace.server"
    | "vsrocq.path"
    | "vsrocq.args"
    | "vsrocq.memory.limit"
    | "vsrocq.interrupt.preempt"
    | "vsrocq.goals.auto"
    | "vsrocq.goals.display"
    | "vsrocq.goals.ppmode"
    | "vsrocq.goals.messages.full"
    | "vsrocq.goals.maxDepth"
    | "vsrocq.proof.mode"
    | "vsrocq.proof.pointInterpretationMode"
    | "vsrocq.proof.cursor.sticky"
    | "vsrocq.proof.delegation"
    | "vsrocq.proof.workers"
    | "vsrocq.proof.block"
    | "vsrocq.proof.display-buttons"
    | "vsrocq.completion.enable"
    | "vsrocq.completion.unificationLimit"
    | "vsrocq.completion.algorithm"
    | "vsrocq.diagnostics.full";

export interface ConfigKeyTypeMap {
    "vsrocq-language-server.trace.server":
        | "off"
        | "messages"
        | "compact"
        | "verbose";
    "vsrocq.path": string;
    "vsrocq.args": unknown[];
    "vsrocq.memory.limit": number;
    "vsrocq.interrupt.preempt": boolean;
    "vsrocq.goals.auto": boolean;
    "vsrocq.goals.display": "Tabs" | "List";
    "vsrocq.goals.ppmode": "Pp";
    "vsrocq.goals.messages.full": boolean;
    "vsrocq.goals.maxDepth": number;
    "vsrocq.proof.mode": number;
    "vsrocq.proof.pointInterpretationMode": number;
    "vsrocq.proof.cursor.sticky": boolean;
    "vsrocq.proof.delegation": "None" | "Skip" | "Delegate";
    "vsrocq.proof.workers": number;
    "vsrocq.proof.block": boolean;
    "vsrocq.proof.display-buttons": boolean;
    "vsrocq.completion.enable": boolean;
    "vsrocq.completion.unificationLimit": number;
    "vsrocq.completion.algorithm": number;
    "vsrocq.diagnostics.full": boolean;
}

export interface ConfigShorthandMap {
    vsrocqLanguageServerTraceServer: "vsrocq-language-server.trace.server";
    path: "vsrocq.path";
    args: "vsrocq.args";
    memoryLimit: "vsrocq.memory.limit";
    interruptPreempt: "vsrocq.interrupt.preempt";
    goalsAuto: "vsrocq.goals.auto";
    goalsDisplay: "vsrocq.goals.display";
    goalsPpmode: "vsrocq.goals.ppmode";
    goalsMessagesFull: "vsrocq.goals.messages.full";
    goalsMaxDepth: "vsrocq.goals.maxDepth";
    proofMode: "vsrocq.proof.mode";
    proofPointInterpretationMode: "vsrocq.proof.pointInterpretationMode";
    proofCursorSticky: "vsrocq.proof.cursor.sticky";
    proofDelegation: "vsrocq.proof.delegation";
    proofWorkers: "vsrocq.proof.workers";
    proofBlock: "vsrocq.proof.block";
    proofDisplayButtons: "vsrocq.proof.display-buttons";
    completionEnable: "vsrocq.completion.enable";
    completionUnificationLimit: "vsrocq.completion.unificationLimit";
    completionAlgorithm: "vsrocq.completion.algorithm";
    diagnosticsFull: "vsrocq.diagnostics.full";
}

export interface ConfigShorthandTypeMap {
    vsrocqLanguageServerTraceServer: "off" | "messages" | "compact" | "verbose";
    path: string;
    args: unknown[];
    memoryLimit: number;
    interruptPreempt: boolean;
    goalsAuto: boolean;
    goalsDisplay: "Tabs" | "List";
    goalsPpmode: "Pp";
    goalsMessagesFull: boolean;
    goalsMaxDepth: number;
    proofMode: number;
    proofPointInterpretationMode: number;
    proofCursorSticky: boolean;
    proofDelegation: "None" | "Skip" | "Delegate";
    proofWorkers: number;
    proofBlock: boolean;
    proofDisplayButtons: boolean;
    completionEnable: boolean;
    completionUnificationLimit: number;
    completionAlgorithm: number;
    diagnosticsFull: boolean;
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
    key: T;
    default: ConfigKeyTypeMap[T];
}

/**
 * Configs map registered by `rocq-prover.vsrocq`
 */
export const configs = {
    /**
     * Traces the communication between VS Code and the language server.
     * @key `vsrocq-language-server.trace.server`
     * @default `"off"`
     * @type `string`
     */
    vsrocqLanguageServerTraceServer: {
        key: "vsrocq-language-server.trace.server",
        default: "off",
    } as ConfigItem<"vsrocq-language-server.trace.server">,
    /**
     * Path to vsrocqtop.
     * @key `vsrocq.path`
     * @default `""`
     * @type `string`
     */
    path: {
        key: "vsrocq.path",
        default: "",
    } as ConfigItem<"vsrocq.path">,
    /**
     * vsrocqtop arguments
     * @key `vsrocq.args`
     * @default `[]`
     * @type `array`
     */
    args: {
        key: "vsrocq.args",
        default: [],
    } as ConfigItem<"vsrocq.args">,
    /**
     * Sets the memory limit over which we discard the execution state of documents which have been saved (in Gb).
     * @key `vsrocq.memory.limit`
     * @default `4`
     * @type `number`
     */
    memoryLimit: {
        key: "vsrocq.memory.limit",
        default: 4,
    } as ConfigItem<"vsrocq.memory.limit">,
    /**
     * Hovering and other queries preempt checking tasks (recommended Rocq >= 9.3).
     * @key `vsrocq.interrupt.preempt`
     * @default `false`
     * @type `boolean`
     */
    interruptPreempt: {
        key: "vsrocq.interrupt.preempt",
        default: false,
    } as ConfigItem<"vsrocq.interrupt.preempt">,
    /**
     * Should the goal view automatically display when navigating a rocq document.
     * @key `vsrocq.goals.auto`
     * @default `true`
     * @type `boolean`
     */
    goalsAuto: {
        key: "vsrocq.goals.auto",
        default: true,
    } as ConfigItem<"vsrocq.goals.auto">,
    /**
     * Determines whether multiple goals should be displayed in different tabs or as a list of collapsible items.
     * @key `vsrocq.goals.display`
     * @default `"List"`
     * @type `string`
     */
    goalsDisplay: {
        key: "vsrocq.goals.display",
        default: "List",
    } as ConfigItem<"vsrocq.goals.display">,
    /**
     * This read-only setting is to indicate to the server to send goals in pretty printed format instead of plain text.
     * @key `vsrocq.goals.ppmode`
     * @default `"Pp"`
     * @type `string`
     */
    goalsPpmode: {
        key: "vsrocq.goals.ppmode",
        default: "Pp",
    } as ConfigItem<"vsrocq.goals.ppmode">,
    /**
     *
     * @key `vsrocq.goals.messages.full`
     * @default `true`
     * @type `boolean`
     */
    goalsMessagesFull: {
        key: "vsrocq.goals.messages.full",
        default: true,
    } as ConfigItem<"vsrocq.goals.messages.full">,
    /**
     *
     * @key `vsrocq.goals.maxDepth`
     * @default `17`
     * @type `number`
     */
    goalsMaxDepth: {
        key: "vsrocq.goals.maxDepth",
        default: 17,
    } as ConfigItem<"vsrocq.goals.maxDepth">,
    /**
     * Configures the proof checking mode for rocq.
     * @key `vsrocq.proof.mode`
     * @default `0`
     * @type `number`
     */
    proofMode: {
        key: "vsrocq.proof.mode",
        default: 0,
    } as ConfigItem<"vsrocq.proof.mode">,
    /**
     * Determines the point to which the proof should be checked when using the `Interpret to point` command.
     * @key `vsrocq.proof.pointInterpretationMode`
     * @default `0`
     * @type `number`
     */
    proofPointInterpretationMode: {
        key: "vsrocq.proof.pointInterpretationMode",
        default: 0,
    } as ConfigItem<"vsrocq.proof.pointInterpretationMode">,
    /**
     * Move the editor's cursor position as Rocq interactively steps forward/backward a command
     * @key `vsrocq.proof.cursor.sticky`
     * @default `true`
     * @type `boolean`
     */
    proofCursorSticky: {
        key: "vsrocq.proof.cursor.sticky",
        default: true,
    } as ConfigItem<"vsrocq.proof.cursor.sticky">,
    /**
     * Determines which delegation strategy should be used by the server.
     * @key `vsrocq.proof.delegation`
     * @default `"None"`
     * @type `string`
     */
    proofDelegation: {
        key: "vsrocq.proof.delegation",
        default: "None",
    } as ConfigItem<"vsrocq.proof.delegation">,
    /**
     * Amount of workers assigned to proofs in delegation mode
     * @key `vsrocq.proof.workers`
     * @default `1`
     * @type `number`
     */
    proofWorkers: {
        key: "vsrocq.proof.workers",
        default: 1,
    } as ConfigItem<"vsrocq.proof.workers">,
    /**
     * Should execution be halted after reaching the first error ?
     * @key `vsrocq.proof.block`
     * @default `true`
     * @type `boolean`
     */
    proofBlock: {
        key: "vsrocq.proof.block",
        default: true,
    } as ConfigItem<"vsrocq.proof.block">,
    /**
     * Toggles whether the Rocq buttons are displayed in the editor actions tab menu.
     * @key `vsrocq.proof.display-buttons`
     * @default `true`
     * @type `boolean`
     */
    proofDisplayButtons: {
        key: "vsrocq.proof.display-buttons",
        default: true,
    } as ConfigItem<"vsrocq.proof.display-buttons">,
    /**
     * Enable completion support from the vsrocq language server
     * @key `vsrocq.completion.enable`
     * @default `false`
     * @type `boolean`
     */
    completionEnable: {
        key: "vsrocq.completion.enable",
        default: false,
    } as ConfigItem<"vsrocq.completion.enable">,
    /**
     * Sets the limit for how many theorems unification is attempted for when attempting code completion for the application of theorems. This determines which theorems can be marked as applicable. The higher the limit, the better results will be, but the slower code completion will be.
     * @key `vsrocq.completion.unificationLimit`
     * @default `100`
     * @type `number`
     */
    completionUnificationLimit: {
        key: "vsrocq.completion.unificationLimit",
        default: 100,
    } as ConfigItem<"vsrocq.completion.unificationLimit">,
    /**
     * Configures the ranking algorithm for auto completions in rocq.
     * @key `vsrocq.completion.algorithm`
     * @default `1`
     * @type `number`
     */
    completionAlgorithm: {
        key: "vsrocq.completion.algorithm",
        default: 1,
    } as ConfigItem<"vsrocq.completion.algorithm">,
    /**
     * Include info in diagnostics
     * @key `vsrocq.diagnostics.full`
     * @default `false`
     * @type `boolean`
     */
    diagnosticsFull: {
        key: "vsrocq.diagnostics.full",
        default: false,
    } as ConfigItem<"vsrocq.diagnostics.full">,
};

export interface ScopedConfigKeyTypeMap {
    path: string;
    args: unknown[];
    "memory.limit": number;
    "interrupt.preempt": boolean;
    "goals.auto": boolean;
    "goals.display": "Tabs" | "List";
    "goals.ppmode": "Pp";
    "goals.messages.full": boolean;
    "goals.maxDepth": number;
    "proof.mode": number;
    "proof.pointInterpretationMode": number;
    "proof.cursor.sticky": boolean;
    "proof.delegation": "None" | "Skip" | "Delegate";
    "proof.workers": number;
    "proof.block": boolean;
    "proof.display-buttons": boolean;
    "completion.enable": boolean;
    "completion.unificationLimit": number;
    "completion.algorithm": number;
    "diagnostics.full": boolean;
}

export const scopedConfigs = {
    scope: "vsrocq",
    defaults: {
        path: "",
        args: [],
        "memory.limit": 4,
        "interrupt.preempt": false,
        "goals.auto": true,
        "goals.display": "List",
        "goals.ppmode": "Pp",
        "goals.messages.full": true,
        "goals.maxDepth": 17,
        "proof.mode": 0,
        "proof.pointInterpretationMode": 0,
        "proof.cursor.sticky": true,
        "proof.delegation": "None",
        "proof.workers": 1,
        "proof.block": true,
        "proof.display-buttons": true,
        "completion.enable": false,
        "completion.unificationLimit": 100,
        "completion.algorithm": 1,
        "diagnostics.full": false,
    } satisfies ScopedConfigKeyTypeMap,
};

export interface NestedConfigs {
    "vsrocq-language-server": {
        trace: {
            server: "off" | "messages" | "compact" | "verbose";
        };
    };
    vsrocq: {
        path: string;
        args: unknown[];
        memory: {
            limit: number;
        };
        interrupt: {
            preempt: boolean;
        };
        goals: {
            auto: boolean;
            display: "Tabs" | "List";
            ppmode: "Pp";
            messages: {
                full: boolean;
            };
            maxDepth: number;
        };
        proof: {
            mode: number;
            pointInterpretationMode: number;
            cursor: {
                sticky: boolean;
            };
            delegation: "None" | "Skip" | "Delegate";
            workers: number;
            block: boolean;
            "display-buttons": boolean;
        };
        completion: {
            enable: boolean;
            unificationLimit: number;
            algorithm: number;
        };
        diagnostics: {
            full: boolean;
        };
    };
}

export interface NestedScopedConfigs {
    path: string;
    args: unknown[];
    memory: {
        limit: number;
    };
    interrupt: {
        preempt: boolean;
    };
    goals: {
        auto: boolean;
        display: "Tabs" | "List";
        ppmode: "Pp";
        messages: {
            full: boolean;
        };
        maxDepth: number;
    };
    proof: {
        mode: number;
        pointInterpretationMode: number;
        cursor: {
            sticky: boolean;
        };
        delegation: "None" | "Skip" | "Delegate";
        workers: number;
        block: boolean;
        "display-buttons": boolean;
    };
    completion: {
        enable: boolean;
        unificationLimit: number;
        algorithm: number;
    };
    diagnostics: {
        full: boolean;
    };
}
